# Generated by Django 5.2.16 on 2026-07-28 06:58

import apps.model_utils
import apps.projects.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='슬러그')),
                ('summary', models.CharField(max_length=300, verbose_name='요약')),
                ('description', models.TextField(verbose_name='설명')),
                ('technologies', models.JSONField(blank=True, default=list, validators=[apps.projects.models.validate_technologies], verbose_name='기술 스택')),
                ('repository_url', models.URLField(blank=True, verbose_name='저장소 URL')),
                ('live_url', models.URLField(blank=True, verbose_name='서비스 URL')),
                ('thumbnail', models.ImageField(blank=True, upload_to='projects/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.model_utils.validate_image_size], verbose_name='대표 이미지')),
                ('status', models.CharField(choices=[('draft', '초안'), ('published', '공개'), ('archived', '보관')], default='draft', max_length=16, verbose_name='상태')),
                ('is_featured', models.BooleanField(default=False, verbose_name='대표 프로젝트')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='공개일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_featured', '-published_at', '-created_at'),
            },
        ),
    ]
