# Generated by Django 5.2.16 on 2026-07-29 04:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('guestbook', '0002_guestbookentry_author'),
        ('users', '0002_user_email_verified_user_email_verified_at_auditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'username은 영문 소문자, 숫자, 밑줄만 사용할 수 있습니다.')]),
        ),
        migrations.CreateModel(
            name='ImpersonationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_reports', to='comments.comment')),
                ('guestbook_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_reports', to='guestbook.guestbookentry')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impersonation report',
                'verbose_name_plural': 'Impersonation reports',
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', False), ('guestbook_entry__isnull', True)), models.Q(('comment__isnull', True), ('guestbook_entry__isnull', False)), _connector='OR'), name='impersonation_report_has_one_target')],
            },
        ),
    ]
