# Generated by Django 5.2.16 on 2026-07-30 08:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AimBestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_ms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(500)])),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aim_best_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('score_ms', 'achieved_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='AimChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aim_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
