# Generated by Django 5.2.16 on 2026-07-28 06:58

import apps.model_utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='이름')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='슬러그')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='설명')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('ordering', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='이름')),
                ('slug', models.SlugField(allow_unicode=True, max_length=70, unique=True, verbose_name='슬러그')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, max_length=240, unique=True, verbose_name='슬러그')),
                ('excerpt', models.CharField(max_length=320, verbose_name='요약')),
                ('content', models.TextField(verbose_name='본문')),
                ('cover_image', models.ImageField(blank=True, upload_to='posts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.model_utils.validate_image_size], verbose_name='대표 이미지')),
                ('status', models.CharField(choices=[('draft', '초안'), ('published', '공개'), ('archived', '보관')], default='draft', max_length=16, verbose_name='상태')),
                ('is_featured', models.BooleanField(default=False, verbose_name='대표 게시글')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='공개일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='posts.tag')),
            ],
            options={
                'ordering': ('-is_featured', '-published_at', '-created_at'),
            },
        ),
    ]
