# Generated by Django 5.2.16 on 2026-07-28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuestbookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="이름")),
                (
                    "message",
                    models.TextField(
                        max_length=500,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="메시지",
                    ),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="공개")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="작성일")),
            ],
            options={
                "verbose_name": "방문록 글",
                "verbose_name_plural": "방문록 글",
                "ordering": ("-created_at",),
            },
        ),
    ]
